# CM hardware
BOARD_HARDWARE_CLASS := $(LOCAL_PATH)/cmhw

# MTK Hardware
BOARD_USES_MTK_HARDWARE := true
BOARD_HAS_MTK_HARDWARE := true
MTK_HARDWARE := true

TARGET_KMODULES := true

BOARD_GLOBAL_CFLAGS += -DADD_LEGACY_ACQUIRE_BUFFER_SYMBOL

#Software gatekeeper
BOARD_USE_SOFT_GATEKEEPER := true

# HIDL Manifest
DEVICE_MANIFEST_FILE := $(DEVICE_PATH)/configs/manifest.xml
